"""
Django settings for lab project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a)u36ai&td=_wz_aza0ylu*tt69bg9g@7ht*0@#m=yuwuzwgvd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# C:\Users\lucaf\OneDrive\Escritorio\GitHub\Backend\lab\lab\settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'rest_framework',
    'corsheaders',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'lab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# C:\Users\lucaf\OneDrive\Escritorio\GitHub\Backend\lab\lab\settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        
        'NAME': 'labinfra',
        
        'USER': 'postgres',      # Ej: 'postgres' o el usuario que creaste
        'PASSWORD': 'Lucaymathi_25', # La contraseña que te permite acceso a PostgreSQL
        'HOST': 'localhost',              
        'PORT': '3634',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO 
# =========================================================================
# settings.py (Ejemplo con SendGrid)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# Usa tu clave de API de SendGrid como contraseña
EMAIL_HOST_PASSWORD = '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' 
# Usa el correo que verificaste en SendGrid
EMAIL_HOST_USER = 'apikey' # El usuario es siempre 'apikey' en SendGrid
DEFAULT_FROM_EMAIL = 'luca.ferreira@estudiantes.utec.edu.uy'

# ********** CONFIGURACIÓN CORS (Solo para Desarrollo Local) **********

# 1. Permite peticiones de cualquier origen (NECESARIO para que index.html funcione localmente)
CORS_ALLOW_ALL_ORIGINS = True

